//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEME
    {
        public int ID_Iteme { get; set; }
        public string Type_Iteme { get; set; }
        public Nullable<decimal> QONTTE_Iteme { get; set; }
        public Nullable<decimal> Pirce_Iteme { get; set; }
        public Nullable<System.DateTime> DATE_Iteme { get; set; }
        public Nullable<System.DateTime> DATE_Expir_Iteme { get; set; }
        public string Supplier_Iteme { get; set; }
        public Nullable<int> ID_STORE { get; set; }
    }
}
