//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginPage
    {
        public int ID_User { get; set; }
        public string UserName { get; set; }
        public string password { get; set; }
        public string WepFormLoad { get; set; }
        public Nullable<bool> Open_Login { get; set; }
    }
}
