//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_Chat
    {
        public int id_Message { get; set; }
        public string Name_Send_Message { get; set; }
        public string Date_Send { get; set; }
        public string Text_Send { get; set; }
    }
}
