//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_SOFRA
    {
        public int ID_ORDER_SOFRA { get; set; }
        public Nullable<int> QONTTE_ORDER_SOFRA { get; set; }
        public Nullable<decimal> TAX_ORDER_SOFRA { get; set; }
        public Nullable<decimal> SERVICE_ORDER_SOFRA { get; set; }
        public Nullable<int> SOFRA_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public Nullable<int> Namber_Order_Sofra { get; set; }
        public Nullable<System.DateTime> Date_Order_Sofra { get; set; }
    }
}
