//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SamahEntities : DbContext
    {
        public SamahEntities()
            : base("name=SamahEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGRE> CATEGRES { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<Enter_Money> Enter_Money { get; set; }
        public virtual DbSet<familly_Cat> familly_Cat { get; set; }
        public virtual DbSet<G_MODULES> G_MODULES { get; set; }
        public virtual DbSet<G_ReportWebSetting> G_ReportWebSetting { get; set; }
        public virtual DbSet<G_Role> G_Role { get; set; }
        public virtual DbSet<G_RoleModule> G_RoleModule { get; set; }
        public virtual DbSet<G_RoleUsers> G_RoleUsers { get; set; }
        public virtual DbSet<G_SearchForm> G_SearchForm { get; set; }
        public virtual DbSet<G_SearchFormModule> G_SearchFormModule { get; set; }
        public virtual DbSet<G_SearchFormSetting> G_SearchFormSetting { get; set; }
        public virtual DbSet<G_SUB_SYSTEMS> G_SUB_SYSTEMS { get; set; }
        public virtual DbSet<G_SYSTEM> G_SYSTEM { get; set; }
        public virtual DbSet<G_USERS> G_USERS { get; set; }
        public virtual DbSet<ITEME> ITEMEs { get; set; }
        public virtual DbSet<LoginPage> LoginPages { get; set; }
        public virtual DbSet<Message_Chat> Message_Chat { get; set; }
        public virtual DbSet<ORDER_DELIVERY> ORDER_DELIVERY { get; set; }
        public virtual DbSet<ORDER_SOFRA> ORDER_SOFRA { get; set; }
        public virtual DbSet<ORDER_TECAYE> ORDER_TECAYE { get; set; }
        public virtual DbSet<Outlet> Outlets { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<Purchases_Details> Purchases_Details { get; set; }
        public virtual DbSet<Purchases_Master> Purchases_Master { get; set; }
        public virtual DbSet<Report_Parameters> Report_Parameters { get; set; }
        public virtual DbSet<Send_Message> Send_Message { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Settings_Report> Settings_Report { get; set; }
        public virtual DbSet<SOFRA> SOFRAs { get; set; }
        public virtual DbSet<Stock_ORDER_TECAYE> Stock_ORDER_TECAYE { get; set; }
        public virtual DbSet<Stok_ORDER_DELIVERY> Stok_ORDER_DELIVERY { get; set; }
        public virtual DbSet<STORE> STOREs { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Table_two_days> Table_two_days { get; set; }
        public virtual DbSet<The_Gard> The_Gard { get; set; }
        public virtual DbSet<Type_EMPLOYEE> Type_EMPLOYEE { get; set; }
        public virtual DbSet<User_sales> User_sales { get; set; }
        public virtual DbSet<IQ_Outlet> IQ_Outlet { get; set; }
        public virtual DbSet<IQ_Purchases_Details> IQ_Purchases_Details { get; set; }
        public virtual DbSet<IQ_Purchases_Master> IQ_Purchases_Master { get; set; }
        public virtual DbSet<ReviewSalesItemInfo> ReviewSalesItemInfoes { get; set; }
        public virtual DbSet<ReviewSalesMaster> ReviewSalesMasters { get; set; }
    
        public virtual ObjectResult<insert_Table_Result> insert_Table(string name, string phone, string type, string message, string tR_Type)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var tR_TypeParameter = tR_Type != null ?
                new ObjectParameter("TR_Type", tR_Type) :
                new ObjectParameter("TR_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<insert_Table_Result>("insert_Table", nameParameter, phoneParameter, typeParameter, messageParameter, tR_TypeParameter);
        }
    
        public virtual ObjectResult<Delete_Rows_Result> Delete_Rows(Nullable<int> iD, string tR_Type)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tR_TypeParameter = tR_Type != null ?
                new ObjectParameter("TR_Type", tR_Type) :
                new ObjectParameter("TR_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Delete_Rows_Result>("Delete_Rows", iDParameter, tR_TypeParameter);
        }
    
        public virtual ObjectResult<Enter_Customer_Result> Enter_Customer(Nullable<int> iD, string tR_Type)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tR_TypeParameter = tR_Type != null ?
                new ObjectParameter("TR_Type", tR_Type) :
                new ObjectParameter("TR_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Enter_Customer_Result>("Enter_Customer", iDParameter, tR_TypeParameter);
        }
    
        public virtual int insert_tw(string name, Nullable<bool> cheak)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var cheakParameter = cheak.HasValue ?
                new ObjectParameter("cheak", cheak) :
                new ObjectParameter("cheak", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_tw", nameParameter, cheakParameter);
        }
    
        public virtual int Add_Emp(string user_name, string passwrd, string emp_nam, string emp_phone, string type_emp)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            var passwrdParameter = passwrd != null ?
                new ObjectParameter("passwrd", passwrd) :
                new ObjectParameter("passwrd", typeof(string));
    
            var emp_namParameter = emp_nam != null ?
                new ObjectParameter("emp_nam", emp_nam) :
                new ObjectParameter("emp_nam", typeof(string));
    
            var emp_phoneParameter = emp_phone != null ?
                new ObjectParameter("emp_phone", emp_phone) :
                new ObjectParameter("emp_phone", typeof(string));
    
            var type_empParameter = type_emp != null ?
                new ObjectParameter("type_emp", type_emp) :
                new ObjectParameter("type_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Emp", user_nameParameter, passwrdParameter, emp_namParameter, emp_phoneParameter, type_empParameter);
        }
    
        public virtual int Add_Message_Chat(string name_Send_Message, string date_Send, string text_Send)
        {
            var name_Send_MessageParameter = name_Send_Message != null ?
                new ObjectParameter("Name_Send_Message", name_Send_Message) :
                new ObjectParameter("Name_Send_Message", typeof(string));
    
            var date_SendParameter = date_Send != null ?
                new ObjectParameter("Date_Send", date_Send) :
                new ObjectParameter("Date_Send", typeof(string));
    
            var text_SendParameter = text_Send != null ?
                new ObjectParameter("Text_Send", text_Send) :
                new ObjectParameter("Text_Send", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Message_Chat", name_Send_MessageParameter, date_SendParameter, text_SendParameter);
        }
    
        public virtual int Add_Message_open_Uesr(string name_Send_Message, string date_Send, string text_Send, string open_user)
        {
            var name_Send_MessageParameter = name_Send_Message != null ?
                new ObjectParameter("Name_Send_Message", name_Send_Message) :
                new ObjectParameter("Name_Send_Message", typeof(string));
    
            var date_SendParameter = date_Send != null ?
                new ObjectParameter("Date_Send", date_Send) :
                new ObjectParameter("Date_Send", typeof(string));
    
            var text_SendParameter = text_Send != null ?
                new ObjectParameter("Text_Send", text_Send) :
                new ObjectParameter("Text_Send", typeof(string));
    
            var open_userParameter = open_user != null ?
                new ObjectParameter("open_user", open_user) :
                new ObjectParameter("open_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Message_open_Uesr", name_Send_MessageParameter, date_SendParameter, text_SendParameter, open_userParameter);
        }
    
        public virtual int Add_Settings(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Settings", userNameParameter);
        }
    
        public virtual int addemp(string emp_nam, string emp_phone, string usar_name_emp, string passwrd_emp)
        {
            var emp_namParameter = emp_nam != null ?
                new ObjectParameter("emp_nam", emp_nam) :
                new ObjectParameter("emp_nam", typeof(string));
    
            var emp_phoneParameter = emp_phone != null ?
                new ObjectParameter("emp_phone", emp_phone) :
                new ObjectParameter("emp_phone", typeof(string));
    
            var usar_name_empParameter = usar_name_emp != null ?
                new ObjectParameter("usar_name_emp", usar_name_emp) :
                new ObjectParameter("usar_name_emp", typeof(string));
    
            var passwrd_empParameter = passwrd_emp != null ?
                new ObjectParameter("passwrd_emp", passwrd_emp) :
                new ObjectParameter("passwrd_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addemp", emp_namParameter, emp_phoneParameter, usar_name_empParameter, passwrd_empParameter);
        }
    
        public virtual ObjectResult<all_The_Gard_Result> all_The_Gard(string userName, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<all_The_Gard_Result>("all_The_Gard", userNameParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> Date_Time_Now()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("Date_Time_Now");
        }
    
        public virtual int delet_PRODUCT(string pRODUCT_NAME)
        {
            var pRODUCT_NAMEParameter = pRODUCT_NAME != null ?
                new ObjectParameter("PRODUCT_NAME", pRODUCT_NAME) :
                new ObjectParameter("PRODUCT_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delet_PRODUCT", pRODUCT_NAMEParameter);
        }
    
        public virtual int Delete_Cat(string name_CAT)
        {
            var name_CATParameter = name_CAT != null ?
                new ObjectParameter("Name_CAT", name_CAT) :
                new ObjectParameter("Name_CAT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Cat", name_CATParameter);
        }
    
        public virtual int Delete_Notifications(Nullable<int> iD_ORDER_Delivery)
        {
            var iD_ORDER_DeliveryParameter = iD_ORDER_Delivery.HasValue ?
                new ObjectParameter("ID_ORDER_Delivery", iD_ORDER_Delivery) :
                new ObjectParameter("ID_ORDER_Delivery", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Notifications", iD_ORDER_DeliveryParameter);
        }
    
        public virtual int delete_order_in_Notifications(Nullable<int> iD_ORDER_Delivery)
        {
            var iD_ORDER_DeliveryParameter = iD_ORDER_Delivery.HasValue ?
                new ObjectParameter("ID_ORDER_Delivery", iD_ORDER_Delivery) :
                new ObjectParameter("ID_ORDER_Delivery", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_order_in_Notifications", iD_ORDER_DeliveryParameter);
        }
    
        public virtual int Delete_Send_Message(string open_user)
        {
            var open_userParameter = open_user != null ?
                new ObjectParameter("open_user", open_user) :
                new ObjectParameter("open_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Send_Message", open_userParameter);
        }
    
        public virtual ObjectResult<get_emp_Result> get_emp(string newphone)
        {
            var newphoneParameter = newphone != null ?
                new ObjectParameter("newphone", newphone) :
                new ObjectParameter("newphone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_emp_Result>("get_emp", newphoneParameter);
        }
    
        public virtual ObjectResult<Get_Send_Message_Result> Get_Send_Message(string open_user)
        {
            var open_userParameter = open_user != null ?
                new ObjectParameter("open_user", open_user) :
                new ObjectParameter("open_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Send_Message_Result>("Get_Send_Message", open_userParameter);
        }
    
        public virtual ObjectResult<Get_Settings_Result> Get_Settings(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Settings_Result>("Get_Settings", userNameParameter);
        }
    
        public virtual ObjectResult<Get_Settings_Report_Result> Get_Settings_Report(string iD_Button_Print)
        {
            var iD_Button_PrintParameter = iD_Button_Print != null ?
                new ObjectParameter("ID_Button_Print", iD_Button_Print) :
                new ObjectParameter("ID_Button_Print", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Settings_Report_Result>("Get_Settings_Report", iD_Button_PrintParameter);
        }
    
        public virtual ObjectResult<Get_Settings_Report_and_Parameter_Result> Get_Settings_Report_and_Parameter(string iD_Button_Print)
        {
            var iD_Button_PrintParameter = iD_Button_Print != null ?
                new ObjectParameter("ID_Button_Print", iD_Button_Print) :
                new ObjectParameter("ID_Button_Print", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Settings_Report_and_Parameter_Result>("Get_Settings_Report_and_Parameter", iD_Button_PrintParameter);
        }
    
        public virtual ObjectResult<getPRODUCT_NAME_Result> getPRODUCT_NAME(string name_CAT)
        {
            var name_CATParameter = name_CAT != null ?
                new ObjectParameter("Name_CAT", name_CAT) :
                new ObjectParameter("Name_CAT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPRODUCT_NAME_Result>("getPRODUCT_NAME", name_CATParameter);
        }
    
        public virtual int insert_castomer(string cast_name, string cast_addres1, string cast_addres2, string cast_phone)
        {
            var cast_nameParameter = cast_name != null ?
                new ObjectParameter("cast_name", cast_name) :
                new ObjectParameter("cast_name", typeof(string));
    
            var cast_addres1Parameter = cast_addres1 != null ?
                new ObjectParameter("cast_addres1", cast_addres1) :
                new ObjectParameter("cast_addres1", typeof(string));
    
            var cast_addres2Parameter = cast_addres2 != null ?
                new ObjectParameter("cast_addres2", cast_addres2) :
                new ObjectParameter("cast_addres2", typeof(string));
    
            var cast_phoneParameter = cast_phone != null ?
                new ObjectParameter("cast_phone", cast_phone) :
                new ObjectParameter("cast_phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_castomer", cast_nameParameter, cast_addres1Parameter, cast_addres2Parameter, cast_phoneParameter);
        }
    
        public virtual int insert_Cat(string name_CAT)
        {
            var name_CATParameter = name_CAT != null ?
                new ObjectParameter("Name_CAT", name_CAT) :
                new ObjectParameter("Name_CAT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Cat", name_CATParameter);
        }
    
        public virtual int insert_ORDER_DELIVERY(string userName, Nullable<int> namber_Order_Delivery, Nullable<decimal> total_All, string date_Order_Delivery, Nullable<double> tax, Nullable<int> cUSTOMER_ID, string type_order, Nullable<bool> confirmation)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var namber_Order_DeliveryParameter = namber_Order_Delivery.HasValue ?
                new ObjectParameter("Namber_Order_Delivery", namber_Order_Delivery) :
                new ObjectParameter("Namber_Order_Delivery", typeof(int));
    
            var total_AllParameter = total_All.HasValue ?
                new ObjectParameter("Total_All", total_All) :
                new ObjectParameter("Total_All", typeof(decimal));
    
            var date_Order_DeliveryParameter = date_Order_Delivery != null ?
                new ObjectParameter("Date_Order_Delivery", date_Order_Delivery) :
                new ObjectParameter("Date_Order_Delivery", typeof(string));
    
            var taxParameter = tax.HasValue ?
                new ObjectParameter("Tax", tax) :
                new ObjectParameter("Tax", typeof(double));
    
            var cUSTOMER_IDParameter = cUSTOMER_ID.HasValue ?
                new ObjectParameter("CUSTOMER_ID", cUSTOMER_ID) :
                new ObjectParameter("CUSTOMER_ID", typeof(int));
    
            var type_orderParameter = type_order != null ?
                new ObjectParameter("type_order", type_order) :
                new ObjectParameter("type_order", typeof(string));
    
            var confirmationParameter = confirmation.HasValue ?
                new ObjectParameter("Confirmation", confirmation) :
                new ObjectParameter("Confirmation", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_ORDER_DELIVERY", userNameParameter, namber_Order_DeliveryParameter, total_AllParameter, date_Order_DeliveryParameter, taxParameter, cUSTOMER_IDParameter, type_orderParameter, confirmationParameter);
        }
    
        public virtual int insert_ORDER_TECAYE(string userName, Nullable<int> namber_Order_Tecaye, Nullable<decimal> total_All, string date_Order_Tecaye, string type_order)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var namber_Order_TecayeParameter = namber_Order_Tecaye.HasValue ?
                new ObjectParameter("Namber_Order_Tecaye", namber_Order_Tecaye) :
                new ObjectParameter("Namber_Order_Tecaye", typeof(int));
    
            var total_AllParameter = total_All.HasValue ?
                new ObjectParameter("Total_All", total_All) :
                new ObjectParameter("Total_All", typeof(decimal));
    
            var date_Order_TecayeParameter = date_Order_Tecaye != null ?
                new ObjectParameter("Date_Order_Tecaye", date_Order_Tecaye) :
                new ObjectParameter("Date_Order_Tecaye", typeof(string));
    
            var type_orderParameter = type_order != null ?
                new ObjectParameter("type_order", type_order) :
                new ObjectParameter("type_order", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_ORDER_TECAYE", userNameParameter, namber_Order_TecayeParameter, total_AllParameter, date_Order_TecayeParameter, type_orderParameter);
        }
    
        public virtual int insert_Outlet(string dasc_Name, Nullable<decimal> pirce, string userName, string tr_Type)
        {
            var dasc_NameParameter = dasc_Name != null ?
                new ObjectParameter("Dasc_Name", dasc_Name) :
                new ObjectParameter("Dasc_Name", typeof(string));
    
            var pirceParameter = pirce.HasValue ?
                new ObjectParameter("pirce", pirce) :
                new ObjectParameter("pirce", typeof(decimal));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var tr_TypeParameter = tr_Type != null ?
                new ObjectParameter("Tr_Type", tr_Type) :
                new ObjectParameter("Tr_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Outlet", dasc_NameParameter, pirceParameter, userNameParameter, tr_TypeParameter);
        }
    
        public virtual int insert_Stock_ORDER_TECAYE(string name_Product_sell, Nullable<double> quantity_sell, Nullable<decimal> price_One_part, Nullable<decimal> total_Price_One_Part, string notes_Order)
        {
            var name_Product_sellParameter = name_Product_sell != null ?
                new ObjectParameter("Name_Product_sell", name_Product_sell) :
                new ObjectParameter("Name_Product_sell", typeof(string));
    
            var quantity_sellParameter = quantity_sell.HasValue ?
                new ObjectParameter("Quantity_sell", quantity_sell) :
                new ObjectParameter("Quantity_sell", typeof(double));
    
            var price_One_partParameter = price_One_part.HasValue ?
                new ObjectParameter("price_One_part", price_One_part) :
                new ObjectParameter("price_One_part", typeof(decimal));
    
            var total_Price_One_PartParameter = total_Price_One_Part.HasValue ?
                new ObjectParameter("Total_Price_One_Part", total_Price_One_Part) :
                new ObjectParameter("Total_Price_One_Part", typeof(decimal));
    
            var notes_OrderParameter = notes_Order != null ?
                new ObjectParameter("Notes_Order", notes_Order) :
                new ObjectParameter("Notes_Order", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Stock_ORDER_TECAYE", name_Product_sellParameter, quantity_sellParameter, price_One_partParameter, total_Price_One_PartParameter, notes_OrderParameter);
        }
    
        public virtual int insert_Stok_ORDER_DELIVERY(string name_Product_sell, Nullable<double> quantity_sell, Nullable<decimal> price_One_part, Nullable<decimal> total_Price_One_Part, string notes_Order, Nullable<int> fK_ORDER_Delivery)
        {
            var name_Product_sellParameter = name_Product_sell != null ?
                new ObjectParameter("Name_Product_sell", name_Product_sell) :
                new ObjectParameter("Name_Product_sell", typeof(string));
    
            var quantity_sellParameter = quantity_sell.HasValue ?
                new ObjectParameter("Quantity_sell", quantity_sell) :
                new ObjectParameter("Quantity_sell", typeof(double));
    
            var price_One_partParameter = price_One_part.HasValue ?
                new ObjectParameter("price_One_part", price_One_part) :
                new ObjectParameter("price_One_part", typeof(decimal));
    
            var total_Price_One_PartParameter = total_Price_One_Part.HasValue ?
                new ObjectParameter("Total_Price_One_Part", total_Price_One_Part) :
                new ObjectParameter("Total_Price_One_Part", typeof(decimal));
    
            var notes_OrderParameter = notes_Order != null ?
                new ObjectParameter("Notes_Order", notes_Order) :
                new ObjectParameter("Notes_Order", typeof(string));
    
            var fK_ORDER_DeliveryParameter = fK_ORDER_Delivery.HasValue ?
                new ObjectParameter("FK_ORDER_Delivery", fK_ORDER_Delivery) :
                new ObjectParameter("FK_ORDER_Delivery", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Stok_ORDER_DELIVERY", name_Product_sellParameter, quantity_sellParameter, price_One_partParameter, total_Price_One_PartParameter, notes_OrderParameter, fK_ORDER_DeliveryParameter);
        }
    
        public virtual int insert_Table_two_days()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Table_two_days");
        }
    
        public virtual int insrte_ORDER_TECAYE_All(string name_Product_sell, Nullable<double> quantity_sell, Nullable<decimal> price_One_part, Nullable<decimal> total_Price_One_Part, Nullable<decimal> total_All, string userName_EMPLOYEE_ID, Nullable<int> namber_Order_Tecaye)
        {
            var name_Product_sellParameter = name_Product_sell != null ?
                new ObjectParameter("Name_Product_sell", name_Product_sell) :
                new ObjectParameter("Name_Product_sell", typeof(string));
    
            var quantity_sellParameter = quantity_sell.HasValue ?
                new ObjectParameter("Quantity_sell", quantity_sell) :
                new ObjectParameter("Quantity_sell", typeof(double));
    
            var price_One_partParameter = price_One_part.HasValue ?
                new ObjectParameter("price_One_part", price_One_part) :
                new ObjectParameter("price_One_part", typeof(decimal));
    
            var total_Price_One_PartParameter = total_Price_One_Part.HasValue ?
                new ObjectParameter("Total_Price_One_Part", total_Price_One_Part) :
                new ObjectParameter("Total_Price_One_Part", typeof(decimal));
    
            var total_AllParameter = total_All.HasValue ?
                new ObjectParameter("Total_All", total_All) :
                new ObjectParameter("Total_All", typeof(decimal));
    
            var userName_EMPLOYEE_IDParameter = userName_EMPLOYEE_ID != null ?
                new ObjectParameter("UserName_EMPLOYEE_ID", userName_EMPLOYEE_ID) :
                new ObjectParameter("UserName_EMPLOYEE_ID", typeof(string));
    
            var namber_Order_TecayeParameter = namber_Order_Tecaye.HasValue ?
                new ObjectParameter("Namber_Order_Tecaye", namber_Order_Tecaye) :
                new ObjectParameter("Namber_Order_Tecaye", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insrte_ORDER_TECAYE_All", name_Product_sellParameter, quantity_sellParameter, price_One_partParameter, total_Price_One_PartParameter, total_AllParameter, userName_EMPLOYEE_IDParameter, namber_Order_TecayeParameter);
        }
    
        public virtual ObjectResult<Notifications_confirmation_Result> Notifications_confirmation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Notifications_confirmation_Result>("Notifications_confirmation");
        }
    
        public virtual int Notifications_insert_Name_Pilot(Nullable<int> iD_ORDER_Delivery, string name_Pilot)
        {
            var iD_ORDER_DeliveryParameter = iD_ORDER_Delivery.HasValue ?
                new ObjectParameter("ID_ORDER_Delivery", iD_ORDER_Delivery) :
                new ObjectParameter("ID_ORDER_Delivery", typeof(int));
    
            var name_PilotParameter = name_Pilot != null ?
                new ObjectParameter("Name_Pilot", name_Pilot) :
                new ObjectParameter("Name_Pilot", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Notifications_insert_Name_Pilot", iD_ORDER_DeliveryParameter, name_PilotParameter);
        }
    
        public virtual int Notifications_successful(Nullable<int> iD_ORDER_Delivery)
        {
            var iD_ORDER_DeliveryParameter = iD_ORDER_Delivery.HasValue ?
                new ObjectParameter("ID_ORDER_Delivery", iD_ORDER_Delivery) :
                new ObjectParameter("ID_ORDER_Delivery", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Notifications_successful", iD_ORDER_DeliveryParameter);
        }
    
        public virtual int open_and_close_Login(string userName, string password, Nullable<bool> open_Login)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var open_LoginParameter = open_Login.HasValue ?
                new ObjectParameter("Open_Login", open_Login) :
                new ObjectParameter("Open_Login", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("open_and_close_Login", userNameParameter, passwordParameter, open_LoginParameter);
        }
    
        public virtual ObjectResult<Receipt_Order_delivery_one_Result> Receipt_Order_delivery_one(Nullable<int> iD_ORDER_Delivery)
        {
            var iD_ORDER_DeliveryParameter = iD_ORDER_Delivery.HasValue ?
                new ObjectParameter("ID_ORDER_Delivery", iD_ORDER_Delivery) :
                new ObjectParameter("ID_ORDER_Delivery", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Receipt_Order_delivery_one_Result>("Receipt_Order_delivery_one", iD_ORDER_DeliveryParameter);
        }
    
        public virtual ObjectResult<Receipt_Order_delivery_two_Result> Receipt_Order_delivery_two(Nullable<int> iD_ORDER_Delivery)
        {
            var iD_ORDER_DeliveryParameter = iD_ORDER_Delivery.HasValue ?
                new ObjectParameter("ID_ORDER_Delivery", iD_ORDER_Delivery) :
                new ObjectParameter("ID_ORDER_Delivery", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Receipt_Order_delivery_two_Result>("Receipt_Order_delivery_two", iD_ORDER_DeliveryParameter);
        }
    
        public virtual ObjectResult<Receipt_Order_Teky_one_Result> Receipt_Order_Teky_one()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Receipt_Order_Teky_one_Result>("Receipt_Order_Teky_one");
        }
    
        public virtual ObjectResult<Receipt_Order_Teky_two_Result> Receipt_Order_Teky_two()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Receipt_Order_Teky_two_Result>("Receipt_Order_Teky_two");
        }
    
        public virtual ObjectResult<search_by_pohne_Result> search_by_pohne(string newphone)
        {
            var newphoneParameter = newphone != null ?
                new ObjectParameter("newphone", newphone) :
                new ObjectParameter("newphone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<search_by_pohne_Result>("search_by_pohne", newphoneParameter);
        }
    
        public virtual ObjectResult<search_PRODUCT_NAME_Result> search_PRODUCT_NAME(string name_CAT, string pRODUCT_NAME)
        {
            var name_CATParameter = name_CAT != null ?
                new ObjectParameter("Name_CAT", name_CAT) :
                new ObjectParameter("Name_CAT", typeof(string));
    
            var pRODUCT_NAMEParameter = pRODUCT_NAME != null ?
                new ObjectParameter("PRODUCT_NAME", pRODUCT_NAME) :
                new ObjectParameter("PRODUCT_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<search_PRODUCT_NAME_Result>("search_PRODUCT_NAME", name_CATParameter, pRODUCT_NAMEParameter);
        }
    
        public virtual ObjectResult<select_All_Message_Result> select_All_Message()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_All_Message_Result>("select_All_Message");
        }
    
        public virtual ObjectResult<Select_All_Open_Uesr_Result> Select_All_Open_Uesr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_All_Open_Uesr_Result>("Select_All_Open_Uesr");
        }
    
        public virtual ObjectResult<string> Select_All_User()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Select_All_User");
        }
    
        public virtual int select_days(ObjectParameter num_Day_out)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("select_days", num_Day_out);
        }
    
        public virtual ObjectResult<Nullable<int>> Select_List_Num_Order()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Select_List_Num_Order");
        }
    
        public virtual ObjectResult<string> select_Pilot()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("select_Pilot");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<spGetNameByUser_Result> spGetNameByUser(string nameUser, string password)
        {
            var nameUserParameter = nameUser != null ?
                new ObjectParameter("NameUser", nameUser) :
                new ObjectParameter("NameUser", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetNameByUser_Result>("spGetNameByUser", nameUserParameter, passwordParameter);
        }
    
        public virtual int spInsertPRODUCT(string pRODUCT_NAME, Nullable<decimal> pRODUCT_PRICE, Nullable<decimal> pRODUCT_QET, string name_CAT)
        {
            var pRODUCT_NAMEParameter = pRODUCT_NAME != null ?
                new ObjectParameter("PRODUCT_NAME", pRODUCT_NAME) :
                new ObjectParameter("PRODUCT_NAME", typeof(string));
    
            var pRODUCT_PRICEParameter = pRODUCT_PRICE.HasValue ?
                new ObjectParameter("PRODUCT_PRICE", pRODUCT_PRICE) :
                new ObjectParameter("PRODUCT_PRICE", typeof(decimal));
    
            var pRODUCT_QETParameter = pRODUCT_QET.HasValue ?
                new ObjectParameter("PRODUCT_QET", pRODUCT_QET) :
                new ObjectParameter("PRODUCT_QET", typeof(decimal));
    
            var name_CATParameter = name_CAT != null ?
                new ObjectParameter("Name_CAT", name_CAT) :
                new ObjectParameter("Name_CAT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertPRODUCT", pRODUCT_NAMEParameter, pRODUCT_PRICEParameter, pRODUCT_QETParameter, name_CATParameter);
        }
    
        public virtual int update_customer(string cUSTOMER_NAME, string cUSTOMER_ADDRES, string cUSTOMER_ADDRES_2, string pHONE, string newphone)
        {
            var cUSTOMER_NAMEParameter = cUSTOMER_NAME != null ?
                new ObjectParameter("CUSTOMER_NAME", cUSTOMER_NAME) :
                new ObjectParameter("CUSTOMER_NAME", typeof(string));
    
            var cUSTOMER_ADDRESParameter = cUSTOMER_ADDRES != null ?
                new ObjectParameter("CUSTOMER_ADDRES", cUSTOMER_ADDRES) :
                new ObjectParameter("CUSTOMER_ADDRES", typeof(string));
    
            var cUSTOMER_ADDRES_2Parameter = cUSTOMER_ADDRES_2 != null ?
                new ObjectParameter("CUSTOMER_ADDRES_2", cUSTOMER_ADDRES_2) :
                new ObjectParameter("CUSTOMER_ADDRES_2", typeof(string));
    
            var pHONEParameter = pHONE != null ?
                new ObjectParameter("PHONE", pHONE) :
                new ObjectParameter("PHONE", typeof(string));
    
            var newphoneParameter = newphone != null ?
                new ObjectParameter("newphone", newphone) :
                new ObjectParameter("newphone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_customer", cUSTOMER_NAMEParameter, cUSTOMER_ADDRESParameter, cUSTOMER_ADDRES_2Parameter, pHONEParameter, newphoneParameter);
        }
    
        public virtual int update_emp(string phone)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_emp", phoneParameter);
        }
    
        public virtual int update_Emp_New(string user_name, string passwrd, string emp_nam, string emp_phone, string emp_phone_New, string type_emp)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            var passwrdParameter = passwrd != null ?
                new ObjectParameter("passwrd", passwrd) :
                new ObjectParameter("passwrd", typeof(string));
    
            var emp_namParameter = emp_nam != null ?
                new ObjectParameter("emp_nam", emp_nam) :
                new ObjectParameter("emp_nam", typeof(string));
    
            var emp_phoneParameter = emp_phone != null ?
                new ObjectParameter("emp_phone", emp_phone) :
                new ObjectParameter("emp_phone", typeof(string));
    
            var emp_phone_NewParameter = emp_phone_New != null ?
                new ObjectParameter("emp_phone_New", emp_phone_New) :
                new ObjectParameter("emp_phone_New", typeof(string));
    
            var type_empParameter = type_emp != null ?
                new ObjectParameter("type_emp", type_emp) :
                new ObjectParameter("type_emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_Emp_New", user_nameParameter, passwrdParameter, emp_namParameter, emp_phoneParameter, emp_phone_NewParameter, type_empParameter);
        }
    
        public virtual int Update_Settings(string nots, string userName)
        {
            var notsParameter = nots != null ?
                new ObjectParameter("Nots", nots) :
                new ObjectParameter("Nots", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Settings", notsParameter, userNameParameter);
        }
    
        public virtual ObjectResult<GetUser_Login_Result> GetUser_Login(string userName, string password, Nullable<bool> open_Login)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var open_LoginParameter = open_Login.HasValue ?
                new ObjectParameter("Open_Login", open_Login) :
                new ObjectParameter("Open_Login", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUser_Login_Result>("GetUser_Login", userNameParameter, passwordParameter, open_LoginParameter);
        }
    
        public virtual int update_SalesReturn(Nullable<int> pRODUCT_ID, Nullable<int> quantity_sell, Nullable<decimal> total_Price_One_Part, Nullable<int> iD_ORDER, string statusFlag)
        {
            var pRODUCT_IDParameter = pRODUCT_ID.HasValue ?
                new ObjectParameter("PRODUCT_ID", pRODUCT_ID) :
                new ObjectParameter("PRODUCT_ID", typeof(int));
    
            var quantity_sellParameter = quantity_sell.HasValue ?
                new ObjectParameter("Quantity_sell", quantity_sell) :
                new ObjectParameter("Quantity_sell", typeof(int));
    
            var total_Price_One_PartParameter = total_Price_One_Part.HasValue ?
                new ObjectParameter("Total_Price_One_Part", total_Price_One_Part) :
                new ObjectParameter("Total_Price_One_Part", typeof(decimal));
    
            var iD_ORDERParameter = iD_ORDER.HasValue ?
                new ObjectParameter("ID_ORDER", iD_ORDER) :
                new ObjectParameter("ID_ORDER", typeof(int));
    
            var statusFlagParameter = statusFlag != null ?
                new ObjectParameter("StatusFlag", statusFlag) :
                new ObjectParameter("StatusFlag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_SalesReturn", pRODUCT_IDParameter, quantity_sellParameter, total_Price_One_PartParameter, iD_ORDERParameter, statusFlagParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> update_Sales_Master(Nullable<decimal> total_All, string userName, Nullable<int> iD_ORDER)
        {
            var total_AllParameter = total_All.HasValue ?
                new ObjectParameter("Total_All", total_All) :
                new ObjectParameter("Total_All", typeof(decimal));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var iD_ORDERParameter = iD_ORDER.HasValue ?
                new ObjectParameter("ID_ORDER", iD_ORDER) :
                new ObjectParameter("ID_ORDER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("update_Sales_Master", total_AllParameter, userNameParameter, iD_ORDERParameter);
        }
    
        public virtual int Close_days()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Close_days");
        }
    
        public virtual int insert_Purchases_Master(string tr_Date, Nullable<int> iD_Supplier, Nullable<bool> type_Debit, Nullable<decimal> total_Amount, Nullable<decimal> paid_Up, Nullable<decimal> to_be_Paid, string rEMARKS)
        {
            var tr_DateParameter = tr_Date != null ?
                new ObjectParameter("Tr_Date", tr_Date) :
                new ObjectParameter("Tr_Date", typeof(string));
    
            var iD_SupplierParameter = iD_Supplier.HasValue ?
                new ObjectParameter("ID_Supplier", iD_Supplier) :
                new ObjectParameter("ID_Supplier", typeof(int));
    
            var type_DebitParameter = type_Debit.HasValue ?
                new ObjectParameter("Type_Debit", type_Debit) :
                new ObjectParameter("Type_Debit", typeof(bool));
    
            var total_AmountParameter = total_Amount.HasValue ?
                new ObjectParameter("Total_Amount", total_Amount) :
                new ObjectParameter("Total_Amount", typeof(decimal));
    
            var paid_UpParameter = paid_Up.HasValue ?
                new ObjectParameter("Paid_Up", paid_Up) :
                new ObjectParameter("Paid_Up", typeof(decimal));
    
            var to_be_PaidParameter = to_be_Paid.HasValue ?
                new ObjectParameter("To_be_Paid", to_be_Paid) :
                new ObjectParameter("To_be_Paid", typeof(decimal));
    
            var rEMARKSParameter = rEMARKS != null ?
                new ObjectParameter("REMARKS", rEMARKS) :
                new ObjectParameter("REMARKS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Purchases_Master", tr_DateParameter, iD_SupplierParameter, type_DebitParameter, total_AmountParameter, paid_UpParameter, to_be_PaidParameter, rEMARKSParameter);
        }
    
        public virtual ObjectResult<string> Processes_Purchases(string pRODUCT_NAME, Nullable<int> pRODUCT_QET, Nullable<decimal> pRODUCT_Purchasing_price, Nullable<decimal> pRODUCT_PRICE, Nullable<decimal> minUnitPrice, string name_CAT, Nullable<int> trNo, Nullable<int> iD_Details, Nullable<int> iD_familly_Cat, string statusFlag)
        {
            var pRODUCT_NAMEParameter = pRODUCT_NAME != null ?
                new ObjectParameter("PRODUCT_NAME", pRODUCT_NAME) :
                new ObjectParameter("PRODUCT_NAME", typeof(string));
    
            var pRODUCT_QETParameter = pRODUCT_QET.HasValue ?
                new ObjectParameter("PRODUCT_QET", pRODUCT_QET) :
                new ObjectParameter("PRODUCT_QET", typeof(int));
    
            var pRODUCT_Purchasing_priceParameter = pRODUCT_Purchasing_price.HasValue ?
                new ObjectParameter("PRODUCT_Purchasing_price", pRODUCT_Purchasing_price) :
                new ObjectParameter("PRODUCT_Purchasing_price", typeof(decimal));
    
            var pRODUCT_PRICEParameter = pRODUCT_PRICE.HasValue ?
                new ObjectParameter("PRODUCT_PRICE", pRODUCT_PRICE) :
                new ObjectParameter("PRODUCT_PRICE", typeof(decimal));
    
            var minUnitPriceParameter = minUnitPrice.HasValue ?
                new ObjectParameter("MinUnitPrice", minUnitPrice) :
                new ObjectParameter("MinUnitPrice", typeof(decimal));
    
            var name_CATParameter = name_CAT != null ?
                new ObjectParameter("Name_CAT", name_CAT) :
                new ObjectParameter("Name_CAT", typeof(string));
    
            var trNoParameter = trNo.HasValue ?
                new ObjectParameter("TrNo", trNo) :
                new ObjectParameter("TrNo", typeof(int));
    
            var iD_DetailsParameter = iD_Details.HasValue ?
                new ObjectParameter("ID_Details", iD_Details) :
                new ObjectParameter("ID_Details", typeof(int));
    
            var iD_familly_CatParameter = iD_familly_Cat.HasValue ?
                new ObjectParameter("ID_familly_Cat", iD_familly_Cat) :
                new ObjectParameter("ID_familly_Cat", typeof(int));
    
            var statusFlagParameter = statusFlag != null ?
                new ObjectParameter("StatusFlag", statusFlag) :
                new ObjectParameter("StatusFlag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Processes_Purchases", pRODUCT_NAMEParameter, pRODUCT_QETParameter, pRODUCT_Purchasing_priceParameter, pRODUCT_PRICEParameter, minUnitPriceParameter, name_CATParameter, trNoParameter, iD_DetailsParameter, iD_familly_CatParameter, statusFlagParameter);
        }
    
        public virtual int update_Purchases_Master(Nullable<int> trNo, string tr_Date, Nullable<int> iD_Supplier, Nullable<bool> type_Debit, Nullable<decimal> total_Amount, Nullable<decimal> paid_Up, Nullable<decimal> to_be_Paid, string rEMARKS)
        {
            var trNoParameter = trNo.HasValue ?
                new ObjectParameter("TrNo", trNo) :
                new ObjectParameter("TrNo", typeof(int));
    
            var tr_DateParameter = tr_Date != null ?
                new ObjectParameter("Tr_Date", tr_Date) :
                new ObjectParameter("Tr_Date", typeof(string));
    
            var iD_SupplierParameter = iD_Supplier.HasValue ?
                new ObjectParameter("ID_Supplier", iD_Supplier) :
                new ObjectParameter("ID_Supplier", typeof(int));
    
            var type_DebitParameter = type_Debit.HasValue ?
                new ObjectParameter("Type_Debit", type_Debit) :
                new ObjectParameter("Type_Debit", typeof(bool));
    
            var total_AmountParameter = total_Amount.HasValue ?
                new ObjectParameter("Total_Amount", total_Amount) :
                new ObjectParameter("Total_Amount", typeof(decimal));
    
            var paid_UpParameter = paid_Up.HasValue ?
                new ObjectParameter("Paid_Up", paid_Up) :
                new ObjectParameter("Paid_Up", typeof(decimal));
    
            var to_be_PaidParameter = to_be_Paid.HasValue ?
                new ObjectParameter("To_be_Paid", to_be_Paid) :
                new ObjectParameter("To_be_Paid", typeof(decimal));
    
            var rEMARKSParameter = rEMARKS != null ?
                new ObjectParameter("REMARKS", rEMARKS) :
                new ObjectParameter("REMARKS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_Purchases_Master", trNoParameter, tr_DateParameter, iD_SupplierParameter, type_DebitParameter, total_AmountParameter, paid_UpParameter, to_be_PaidParameter, rEMARKSParameter);
        }
    
        [DbFunction("SamahEntities", "GFunc_GetPrivilage")]
        public virtual IQueryable<GFunc_GetPrivilage_Result> GFunc_GetPrivilage(Nullable<int> comp, Nullable<int> bra, string user, string sys, string sub, string mod)
        {
            var compParameter = comp.HasValue ?
                new ObjectParameter("Comp", comp) :
                new ObjectParameter("Comp", typeof(int));
    
            var braParameter = bra.HasValue ?
                new ObjectParameter("bra", bra) :
                new ObjectParameter("bra", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var sysParameter = sys != null ?
                new ObjectParameter("Sys", sys) :
                new ObjectParameter("Sys", typeof(string));
    
            var subParameter = sub != null ?
                new ObjectParameter("sub", sub) :
                new ObjectParameter("sub", typeof(string));
    
            var modParameter = mod != null ?
                new ObjectParameter("Mod", mod) :
                new ObjectParameter("Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GFunc_GetPrivilage_Result>("[SamahEntities].[GFunc_GetPrivilage](@Comp, @bra, @user, @Sys, @sub, @Mod)", compParameter, braParameter, userParameter, sysParameter, subParameter, modParameter);
        }
    
        [DbFunction("SamahEntities", "GFunc_GetPrivilageRole")]
        public virtual IQueryable<GFunc_GetPrivilageRole_Result> GFunc_GetPrivilageRole(Nullable<int> comp, Nullable<int> bra, string user, string sys, string sub, string mod)
        {
            var compParameter = comp.HasValue ?
                new ObjectParameter("Comp", comp) :
                new ObjectParameter("Comp", typeof(int));
    
            var braParameter = bra.HasValue ?
                new ObjectParameter("bra", bra) :
                new ObjectParameter("bra", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var sysParameter = sys != null ?
                new ObjectParameter("Sys", sys) :
                new ObjectParameter("Sys", typeof(string));
    
            var subParameter = sub != null ?
                new ObjectParameter("sub", sub) :
                new ObjectParameter("sub", typeof(string));
    
            var modParameter = mod != null ?
                new ObjectParameter("Mod", mod) :
                new ObjectParameter("Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GFunc_GetPrivilageRole_Result>("[SamahEntities].[GFunc_GetPrivilageRole](@Comp, @bra, @user, @Sys, @sub, @Mod)", compParameter, braParameter, userParameter, sysParameter, subParameter, modParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Get_Balance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Get_Balance");
        }
    
        public virtual ObjectResult<Nullable<decimal>> Insert_Enter_Money(string dasc_Name, Nullable<decimal> pirce, string userName, string tr_Type)
        {
            var dasc_NameParameter = dasc_Name != null ?
                new ObjectParameter("Dasc_Name", dasc_Name) :
                new ObjectParameter("Dasc_Name", typeof(string));
    
            var pirceParameter = pirce.HasValue ?
                new ObjectParameter("pirce", pirce) :
                new ObjectParameter("pirce", typeof(decimal));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var tr_TypeParameter = tr_Type != null ?
                new ObjectParameter("Tr_Type", tr_Type) :
                new ObjectParameter("Tr_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Insert_Enter_Money", dasc_NameParameter, pirceParameter, userNameParameter, tr_TypeParameter);
        }
    
        public virtual ObjectResult<Stord_Get_Outlet_Result> Stord_Get_Outlet(string fromDate, string toDate, string uSER_CODE, Nullable<int> type)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var uSER_CODEParameter = uSER_CODE != null ?
                new ObjectParameter("USER_CODE", uSER_CODE) :
                new ObjectParameter("USER_CODE", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Stord_Get_Outlet_Result>("Stord_Get_Outlet", fromDateParameter, toDateParameter, uSER_CODEParameter, typeParameter);
        }
    
        public virtual ObjectResult<all_The_Gard_Details_Result> all_The_Gard_Details(string userName, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<all_The_Gard_Details_Result>("all_The_Gard_Details", userNameParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual int insert_EMPLOYEE(string eMPLOYEE_NAME, string uSER_CODE)
        {
            var eMPLOYEE_NAMEParameter = eMPLOYEE_NAME != null ?
                new ObjectParameter("EMPLOYEE_NAME", eMPLOYEE_NAME) :
                new ObjectParameter("EMPLOYEE_NAME", typeof(string));
    
            var uSER_CODEParameter = uSER_CODE != null ?
                new ObjectParameter("USER_CODE", uSER_CODE) :
                new ObjectParameter("USER_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_EMPLOYEE", eMPLOYEE_NAMEParameter, uSER_CODEParameter);
        }
    
        public virtual ObjectResult<Original_Purchases_receipt_Result> Original_Purchases_receipt(Nullable<int> trNo)
        {
            var trNoParameter = trNo.HasValue ?
                new ObjectParameter("TrNo", trNo) :
                new ObjectParameter("TrNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Original_Purchases_receipt_Result>("Original_Purchases_receipt", trNoParameter);
        }
    
        public virtual ObjectResult<Original_sales_receipt_Result> Original_sales_receipt(Nullable<int> trNo)
        {
            var trNoParameter = trNo.HasValue ?
                new ObjectParameter("TrNo", trNo) :
                new ObjectParameter("TrNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Original_sales_receipt_Result>("Original_sales_receipt", trNoParameter);
        }
    }
}
